/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author almir
 */
public class Tela01login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Tela01login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campousuario = new javax.swing.JTextField();
        btsair = new javax.swing.JButton();
        btlogin = new javax.swing.JButton();
        camposenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campousuario.setBackground(new java.awt.Color(203, 139, 67));
        campousuario.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        campousuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campousuario.setBorder(null);
        campousuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        campousuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campousuarioActionPerformed(evt);
            }
        });
        getContentPane().add(campousuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 330, 30));

        btsair.setBackground(new java.awt.Color(203, 139, 67));
        btsair.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btsair.setText("Sair");
        getContentPane().add(btsair, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 560, 100, 30));

        btlogin.setBackground(new java.awt.Color(203, 139, 67));
        btlogin.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btlogin.setText("Login");
        btlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btloginActionPerformed(evt);
            }
        });
        getContentPane().add(btlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 560, 100, 30));

        camposenha.setBackground(new java.awt.Color(203, 139, 67));
        camposenha.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        camposenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        camposenha.setToolTipText("");
        camposenha.setBorder(null);
        camposenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camposenhaActionPerformed(evt);
            }
        });
        getContentPane().add(camposenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 330, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login/Instagram Post Retrato Pet Shop Verde e Amarelo (1366 × 768 px) (3).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setBounds(0, 0, 1459, 776);
    }// </editor-fold>//GEN-END:initComponents

    private void campousuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campousuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campousuarioActionPerformed

    private void camposenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camposenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_camposenhaActionPerformed

    private void btloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btloginActionPerformed
        // TODO add your handling code here:
        new Tela02menu().setVisible(true);
    }//GEN-LAST:event_btloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela01login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela01login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela01login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela01login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela01login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btlogin;
    private javax.swing.JButton btsair;
    private javax.swing.JPasswordField camposenha;
    private javax.swing.JTextField campousuario;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
